name: Deploy to Replicate

on:
  push:
    branches:
      - main  # หรือเปลี่ยนเป็น branch ที่คุณต้องการ deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Cog
        run: |
          pip install cog

      - name: Login to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog login --token "$REPLICATE_API_TOKEN"

      - name: Push to Replicate
        run: cog push r8.im/varoriya/ryuzakiflux
